/*
 * This file is generated by jOOQ.
 */
package br.com.rafaellins.reunioes.jooq;


import br.com.rafaellins.reunioes.jooq.tables.Direcionamento;
import br.com.rafaellins.reunioes.jooq.tables.Participante;
import br.com.rafaellins.reunioes.jooq.tables.Reuniao;
import br.com.rafaellins.reunioes.jooq.tables.ReuniaoDirecionamento;
import br.com.rafaellins.reunioes.jooq.tables.ReuniaoParticipante;
import br.com.rafaellins.reunioes.jooq.tables.records.DirecionamentoRecord;
import br.com.rafaellins.reunioes.jooq.tables.records.ParticipanteRecord;
import br.com.rafaellins.reunioes.jooq.tables.records.ReuniaoDirecionamentoRecord;
import br.com.rafaellins.reunioes.jooq.tables.records.ReuniaoParticipanteRecord;
import br.com.rafaellins.reunioes.jooq.tables.records.ReuniaoRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DirecionamentoRecord> DIRECIONAMENTO_PKEY = UniqueKeys0.DIRECIONAMENTO_PKEY;
    public static final UniqueKey<ParticipanteRecord> PARTICIPANTE_PKEY = UniqueKeys0.PARTICIPANTE_PKEY;
    public static final UniqueKey<ReuniaoRecord> REUNIAO_PKEY = UniqueKeys0.REUNIAO_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DirecionamentoRecord, ParticipanteRecord> DIRECIONAMENTO__FK_DIRECIONAMENTO___PARTICIPANTE = ForeignKeys0.DIRECIONAMENTO__FK_DIRECIONAMENTO___PARTICIPANTE;
    public static final ForeignKey<ReuniaoDirecionamentoRecord, ReuniaoRecord> REUNIAO_DIRECIONAMENTO__FK_REL_REUNIAO_DIRECIONAMENTO___REUNIAO = ForeignKeys0.REUNIAO_DIRECIONAMENTO__FK_REL_REUNIAO_DIRECIONAMENTO___REUNIAO;
    public static final ForeignKey<ReuniaoDirecionamentoRecord, DirecionamentoRecord> REUNIAO_DIRECIONAMENTO__FK_REL_REUNIAO_DIRECIONAMENTO___DIRECIONAMENTO = ForeignKeys0.REUNIAO_DIRECIONAMENTO__FK_REL_REUNIAO_DIRECIONAMENTO___DIRECIONAMENTO;
    public static final ForeignKey<ReuniaoParticipanteRecord, ReuniaoRecord> REUNIAO_PARTICIPANTE__FK_REL_REUNIAO_PARTICIPANTE___REUNIAO = ForeignKeys0.REUNIAO_PARTICIPANTE__FK_REL_REUNIAO_PARTICIPANTE___REUNIAO;
    public static final ForeignKey<ReuniaoParticipanteRecord, ParticipanteRecord> REUNIAO_PARTICIPANTE__FK_REL_REUNIAO_PARTICIPANTE___PARTICIPANTE = ForeignKeys0.REUNIAO_PARTICIPANTE__FK_REL_REUNIAO_PARTICIPANTE___PARTICIPANTE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<DirecionamentoRecord> DIRECIONAMENTO_PKEY = Internal.createUniqueKey(Direcionamento.DIRECIONAMENTO, "direcionamento_pkey", new TableField[] { Direcionamento.DIRECIONAMENTO.ID }, true);
        public static final UniqueKey<ParticipanteRecord> PARTICIPANTE_PKEY = Internal.createUniqueKey(Participante.PARTICIPANTE, "participante_pkey", new TableField[] { Participante.PARTICIPANTE.ID }, true);
        public static final UniqueKey<ReuniaoRecord> REUNIAO_PKEY = Internal.createUniqueKey(Reuniao.REUNIAO, "reuniao_pkey", new TableField[] { Reuniao.REUNIAO.ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<DirecionamentoRecord, ParticipanteRecord> DIRECIONAMENTO__FK_DIRECIONAMENTO___PARTICIPANTE = Internal.createForeignKey(Keys.PARTICIPANTE_PKEY, Direcionamento.DIRECIONAMENTO, "fk_direcionamento___participante", new TableField[] { Direcionamento.DIRECIONAMENTO.PARTICIPANTE_ID }, true);
        public static final ForeignKey<ReuniaoDirecionamentoRecord, ReuniaoRecord> REUNIAO_DIRECIONAMENTO__FK_REL_REUNIAO_DIRECIONAMENTO___REUNIAO = Internal.createForeignKey(Keys.REUNIAO_PKEY, ReuniaoDirecionamento.REUNIAO_DIRECIONAMENTO, "fk_rel_reuniao_direcionamento___reuniao", new TableField[] { ReuniaoDirecionamento.REUNIAO_DIRECIONAMENTO.REUNIAO_ID }, true);
        public static final ForeignKey<ReuniaoDirecionamentoRecord, DirecionamentoRecord> REUNIAO_DIRECIONAMENTO__FK_REL_REUNIAO_DIRECIONAMENTO___DIRECIONAMENTO = Internal.createForeignKey(Keys.DIRECIONAMENTO_PKEY, ReuniaoDirecionamento.REUNIAO_DIRECIONAMENTO, "fk_rel_reuniao_direcionamento___direcionamento", new TableField[] { ReuniaoDirecionamento.REUNIAO_DIRECIONAMENTO.DIRECIONAMENTO_ID }, true);
        public static final ForeignKey<ReuniaoParticipanteRecord, ReuniaoRecord> REUNIAO_PARTICIPANTE__FK_REL_REUNIAO_PARTICIPANTE___REUNIAO = Internal.createForeignKey(Keys.REUNIAO_PKEY, ReuniaoParticipante.REUNIAO_PARTICIPANTE, "fk_rel_reuniao_participante___reuniao", new TableField[] { ReuniaoParticipante.REUNIAO_PARTICIPANTE.REUNIAO_ID }, true);
        public static final ForeignKey<ReuniaoParticipanteRecord, ParticipanteRecord> REUNIAO_PARTICIPANTE__FK_REL_REUNIAO_PARTICIPANTE___PARTICIPANTE = Internal.createForeignKey(Keys.PARTICIPANTE_PKEY, ReuniaoParticipante.REUNIAO_PARTICIPANTE, "fk_rel_reuniao_participante___participante", new TableField[] { ReuniaoParticipante.REUNIAO_PARTICIPANTE.PARTICIPANTE_ID }, true);
    }
}
