/*
 * This file is generated by jOOQ.
 */
package br.com.rafaellins.reunioes.jooq;


import br.com.rafaellins.reunioes.jooq.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1714799698;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.direcionamento</code>.
     */
    public final Direcionamento DIRECIONAMENTO = Direcionamento.DIRECIONAMENTO;

    /**
     * The table <code>public.participante</code>.
     */
    public final Participante PARTICIPANTE = Participante.PARTICIPANTE;

    /**
     * The table <code>public.reuniao</code>.
     */
    public final Reuniao REUNIAO = Reuniao.REUNIAO;

    /**
     * The table <code>public.reuniao_direcionamento</code>.
     */
    public final ReuniaoDirecionamento REUNIAO_DIRECIONAMENTO = ReuniaoDirecionamento.REUNIAO_DIRECIONAMENTO;

    /**
     * The table <code>public.reuniao_participante</code>.
     */
    public final ReuniaoParticipante REUNIAO_PARTICIPANTE = ReuniaoParticipante.REUNIAO_PARTICIPANTE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Direcionamento.DIRECIONAMENTO,
            Participante.PARTICIPANTE,
            Reuniao.REUNIAO,
            ReuniaoDirecionamento.REUNIAO_DIRECIONAMENTO,
            ReuniaoParticipante.REUNIAO_PARTICIPANTE);
    }
}
