/*
 * This file is generated by jOOQ.
 */
package br.com.rafaellins.reunioes.jooq;


import br.com.rafaellins.reunioes.jooq.tables.Direcionamento;
import br.com.rafaellins.reunioes.jooq.tables.Participante;
import br.com.rafaellins.reunioes.jooq.tables.Reuniao;
import br.com.rafaellins.reunioes.jooq.tables.ReuniaoDirecionamento;
import br.com.rafaellins.reunioes.jooq.tables.ReuniaoParticipante;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.direcionamento</code>.
     */
    public static final Direcionamento DIRECIONAMENTO = Direcionamento.DIRECIONAMENTO;

    /**
     * The table <code>public.participante</code>.
     */
    public static final Participante PARTICIPANTE = Participante.PARTICIPANTE;

    /**
     * The table <code>public.reuniao</code>.
     */
    public static final Reuniao REUNIAO = Reuniao.REUNIAO;

    /**
     * The table <code>public.reuniao_direcionamento</code>.
     */
    public static final ReuniaoDirecionamento REUNIAO_DIRECIONAMENTO = ReuniaoDirecionamento.REUNIAO_DIRECIONAMENTO;

    /**
     * The table <code>public.reuniao_participante</code>.
     */
    public static final ReuniaoParticipante REUNIAO_PARTICIPANTE = ReuniaoParticipante.REUNIAO_PARTICIPANTE;
}
