/*
 * This file is generated by jOOQ.
 */
package br.com.rafaellins.reunioes.jooq.tables.records;


import br.com.rafaellins.reunioes.jooq.tables.Direcionamento;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DirecionamentoRecord extends UpdatableRecordImpl<DirecionamentoRecord> implements Record6<UUID, UUID, Integer, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = -392912099;

    /**
     * Setter for <code>public.direcionamento.id</code>.
     */
    public DirecionamentoRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.direcionamento.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.direcionamento.participante_id</code>.
     */
    public DirecionamentoRecord setParticipanteId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.direcionamento.participante_id</code>.
     */
    public UUID getParticipanteId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.direcionamento.ordem</code>.
     */
    public DirecionamentoRecord setOrdem(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.direcionamento.ordem</code>.
     */
    public Integer getOrdem() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.direcionamento.direcionamento</code>.
     */
    public DirecionamentoRecord setDirecionamento(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.direcionamento.direcionamento</code>.
     */
    public String getDirecionamento() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.direcionamento.prazo</code>.
     */
    public DirecionamentoRecord setPrazo(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.direcionamento.prazo</code>.
     */
    public OffsetDateTime getPrazo() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.direcionamento.data_hora_criacao</code>.
     */
    public DirecionamentoRecord setDataHoraCriacao(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.direcionamento.data_hora_criacao</code>.
     */
    public OffsetDateTime getDataHoraCriacao() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, Integer, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, Integer, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Direcionamento.DIRECIONAMENTO.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Direcionamento.DIRECIONAMENTO.PARTICIPANTE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Direcionamento.DIRECIONAMENTO.ORDEM;
    }

    @Override
    public Field<String> field4() {
        return Direcionamento.DIRECIONAMENTO.DIRECIONAMENTO_;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Direcionamento.DIRECIONAMENTO.PRAZO;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Direcionamento.DIRECIONAMENTO.DATA_HORA_CRIACAO;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getParticipanteId();
    }

    @Override
    public Integer component3() {
        return getOrdem();
    }

    @Override
    public String component4() {
        return getDirecionamento();
    }

    @Override
    public OffsetDateTime component5() {
        return getPrazo();
    }

    @Override
    public OffsetDateTime component6() {
        return getDataHoraCriacao();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getParticipanteId();
    }

    @Override
    public Integer value3() {
        return getOrdem();
    }

    @Override
    public String value4() {
        return getDirecionamento();
    }

    @Override
    public OffsetDateTime value5() {
        return getPrazo();
    }

    @Override
    public OffsetDateTime value6() {
        return getDataHoraCriacao();
    }

    @Override
    public DirecionamentoRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public DirecionamentoRecord value2(UUID value) {
        setParticipanteId(value);
        return this;
    }

    @Override
    public DirecionamentoRecord value3(Integer value) {
        setOrdem(value);
        return this;
    }

    @Override
    public DirecionamentoRecord value4(String value) {
        setDirecionamento(value);
        return this;
    }

    @Override
    public DirecionamentoRecord value5(OffsetDateTime value) {
        setPrazo(value);
        return this;
    }

    @Override
    public DirecionamentoRecord value6(OffsetDateTime value) {
        setDataHoraCriacao(value);
        return this;
    }

    @Override
    public DirecionamentoRecord values(UUID value1, UUID value2, Integer value3, String value4, OffsetDateTime value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DirecionamentoRecord
     */
    public DirecionamentoRecord() {
        super(Direcionamento.DIRECIONAMENTO);
    }

    /**
     * Create a detached, initialised DirecionamentoRecord
     */
    public DirecionamentoRecord(UUID id, UUID participanteId, Integer ordem, String direcionamento, OffsetDateTime prazo, OffsetDateTime dataHoraCriacao) {
        super(Direcionamento.DIRECIONAMENTO);

        set(0, id);
        set(1, participanteId);
        set(2, ordem);
        set(3, direcionamento);
        set(4, prazo);
        set(5, dataHoraCriacao);
    }
}
