/*
 * This file is generated by jOOQ.
 */
package br.com.rafaellins.reunioes.jooq.tables.records;


import br.com.rafaellins.reunioes.jooq.tables.Reuniao;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ReuniaoRecord extends UpdatableRecordImpl<ReuniaoRecord> implements Record7<UUID, Boolean, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = -884010722;

    /**
     * Setter for <code>public.reuniao.id</code>.
     */
    public ReuniaoRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.reuniao.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.reuniao.active</code>.
     */
    public ReuniaoRecord setActive(Boolean value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.reuniao.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.reuniao.titulo</code>.
     */
    public ReuniaoRecord setTitulo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.reuniao.titulo</code>.
     */
    public String getTitulo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.reuniao.descricao</code>.
     */
    public ReuniaoRecord setDescricao(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.reuniao.descricao</code>.
     */
    public String getDescricao() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.reuniao.data_hora</code>.
     */
    public ReuniaoRecord setDataHora(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.reuniao.data_hora</code>.
     */
    public OffsetDateTime getDataHora() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.reuniao.data_hora_criacao</code>.
     */
    public ReuniaoRecord setDataHoraCriacao(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.reuniao.data_hora_criacao</code>.
     */
    public OffsetDateTime getDataHoraCriacao() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.reuniao.data_hora_ultima_atualizacao</code>.
     */
    public ReuniaoRecord setDataHoraUltimaAtualizacao(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.reuniao.data_hora_ultima_atualizacao</code>.
     */
    public OffsetDateTime getDataHoraUltimaAtualizacao() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, Boolean, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, Boolean, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Reuniao.REUNIAO.ID;
    }

    @Override
    public Field<Boolean> field2() {
        return Reuniao.REUNIAO.ACTIVE;
    }

    @Override
    public Field<String> field3() {
        return Reuniao.REUNIAO.TITULO;
    }

    @Override
    public Field<String> field4() {
        return Reuniao.REUNIAO.DESCRICAO;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Reuniao.REUNIAO.DATA_HORA;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Reuniao.REUNIAO.DATA_HORA_CRIACAO;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return Reuniao.REUNIAO.DATA_HORA_ULTIMA_ATUALIZACAO;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public Boolean component2() {
        return getActive();
    }

    @Override
    public String component3() {
        return getTitulo();
    }

    @Override
    public String component4() {
        return getDescricao();
    }

    @Override
    public OffsetDateTime component5() {
        return getDataHora();
    }

    @Override
    public OffsetDateTime component6() {
        return getDataHoraCriacao();
    }

    @Override
    public OffsetDateTime component7() {
        return getDataHoraUltimaAtualizacao();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public Boolean value2() {
        return getActive();
    }

    @Override
    public String value3() {
        return getTitulo();
    }

    @Override
    public String value4() {
        return getDescricao();
    }

    @Override
    public OffsetDateTime value5() {
        return getDataHora();
    }

    @Override
    public OffsetDateTime value6() {
        return getDataHoraCriacao();
    }

    @Override
    public OffsetDateTime value7() {
        return getDataHoraUltimaAtualizacao();
    }

    @Override
    public ReuniaoRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ReuniaoRecord value2(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public ReuniaoRecord value3(String value) {
        setTitulo(value);
        return this;
    }

    @Override
    public ReuniaoRecord value4(String value) {
        setDescricao(value);
        return this;
    }

    @Override
    public ReuniaoRecord value5(OffsetDateTime value) {
        setDataHora(value);
        return this;
    }

    @Override
    public ReuniaoRecord value6(OffsetDateTime value) {
        setDataHoraCriacao(value);
        return this;
    }

    @Override
    public ReuniaoRecord value7(OffsetDateTime value) {
        setDataHoraUltimaAtualizacao(value);
        return this;
    }

    @Override
    public ReuniaoRecord values(UUID value1, Boolean value2, String value3, String value4, OffsetDateTime value5, OffsetDateTime value6, OffsetDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReuniaoRecord
     */
    public ReuniaoRecord() {
        super(Reuniao.REUNIAO);
    }

    /**
     * Create a detached, initialised ReuniaoRecord
     */
    public ReuniaoRecord(UUID id, Boolean active, String titulo, String descricao, OffsetDateTime dataHora, OffsetDateTime dataHoraCriacao, OffsetDateTime dataHoraUltimaAtualizacao) {
        super(Reuniao.REUNIAO);

        set(0, id);
        set(1, active);
        set(2, titulo);
        set(3, descricao);
        set(4, dataHora);
        set(5, dataHoraCriacao);
        set(6, dataHoraUltimaAtualizacao);
    }
}
