/*
 * This file is generated by jOOQ.
 */
package br.com.rafaellins.reunioes.jooq.tables.records;


import br.com.rafaellins.reunioes.jooq.tables.ReuniaoDirecionamento;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReuniaoDirecionamentoRecord extends TableRecordImpl<ReuniaoDirecionamentoRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = -498499913;

    /**
     * Setter for <code>public.reuniao_direcionamento.reuniao_id</code>.
     */
    public ReuniaoDirecionamentoRecord setReuniaoId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.reuniao_direcionamento.reuniao_id</code>.
     */
    public UUID getReuniaoId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.reuniao_direcionamento.direcionamento_id</code>.
     */
    public ReuniaoDirecionamentoRecord setDirecionamentoId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.reuniao_direcionamento.direcionamento_id</code>.
     */
    public UUID getDirecionamentoId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ReuniaoDirecionamento.REUNIAO_DIRECIONAMENTO.REUNIAO_ID;
    }

    @Override
    public Field<UUID> field2() {
        return ReuniaoDirecionamento.REUNIAO_DIRECIONAMENTO.DIRECIONAMENTO_ID;
    }

    @Override
    public UUID component1() {
        return getReuniaoId();
    }

    @Override
    public UUID component2() {
        return getDirecionamentoId();
    }

    @Override
    public UUID value1() {
        return getReuniaoId();
    }

    @Override
    public UUID value2() {
        return getDirecionamentoId();
    }

    @Override
    public ReuniaoDirecionamentoRecord value1(UUID value) {
        setReuniaoId(value);
        return this;
    }

    @Override
    public ReuniaoDirecionamentoRecord value2(UUID value) {
        setDirecionamentoId(value);
        return this;
    }

    @Override
    public ReuniaoDirecionamentoRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReuniaoDirecionamentoRecord
     */
    public ReuniaoDirecionamentoRecord() {
        super(ReuniaoDirecionamento.REUNIAO_DIRECIONAMENTO);
    }

    /**
     * Create a detached, initialised ReuniaoDirecionamentoRecord
     */
    public ReuniaoDirecionamentoRecord(UUID reuniaoId, UUID direcionamentoId) {
        super(ReuniaoDirecionamento.REUNIAO_DIRECIONAMENTO);

        set(0, reuniaoId);
        set(1, direcionamentoId);
    }
}
